name: Build
on: push
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Setup python
        with:
          python-version: "3.x"
      - run: |
          pip install setuptools
          pip install build
          python -m build -n
